-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'INTENT_REACTION_RECEIVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'INTENT_COMMENT_RECEIVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'INTENT_REALIZED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'USER_FOLLOWED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'GUARDIAN_ACTION';
